### ISSUE TITLE
omegaconf.errors.ConfigKeyError: Missing key control

### ISSUE THREAD

**Issue by XieZixiUSTC** [CompVis/image2video-synthesis-using-cINNs#1]
python -W ignore generate_samples.py -gpu 0 -dataset landscape -ckpt_path ./models/landscape/stage2/
this is my command,what wrong could you help me ?thanks

**Comment by mdorkenw** [comment]
Hi, thanks for your interest! Did you download the pre-trained models and place them in ./models/... ? 
If this problem still occurs, please share the whole error message here.
